version: "3.8"
services:
  db_gerconta:
    container_name: db_gerconta
    image: postgres:13.2
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
